### ISSUE TITLE
style code sections distinctly

### ISSUE THREAD

**Issue by fbstj** [fbstj/pivot#11]
make sure code examples in template docs are nice

**Comment by fbstj** [comment]
```css
/* colorise code boxes*/
.mw-code { background: white; padding: 1em; margin-bottom: 1em; }
#editform textarea { font-family: monospace; }
```
