### ISSUE TITLE
desktop sidebar is too wide

### ISSUE THREAD

**Issue by fbstj** [fbstj/pivot#12]

**Comment by fbstj** [comment]
```css
/* sidebar width on desktop */
#page-content>.row { display: flex; }
#sidebar { width: fit-content; max-width: 15em; position: sticky; }
#p-cactions { flex-grow: 1; padding-bottom: 0!important; }
```
