### ISSUE TITLE
add more columns on desktop categories

### ISSUE THREAD

**Issue by fbstj** [fbstj/pivot#18]
3 columns has lots of whitespace

**Comment by fbstj** [comment]
this is a modern mediawiki class so adding the following fixed things

```css
/* citation columns */
.mw-references-columns { column-width: auto; }
ol.references { margin-left: 1em; }
```
