### ISSUE TITLE
add borders to thumbnail images

### ISSUE THREAD

**Issue by fbstj** [fbstj/pivot#7]
to make them stand out from content

**Comment by fbstj** [comment]
added the following styles to `pivot.css` to fix this

```css
/* thumbnails (copied from vector) */
.thumb { margin: 1em; margin-top: .5em; }
.thumb.tleft { margin-left: 0; }
.thumb.tright { margin-right: 0; }
.thumbinner {
  border: 1px solid #c8ccd1;
  padding: 3px;
  background-color: #f8f9fa;
  font-size: 94%;
  text-align: center;
  box-sizing: content-box;
}
.thumbimage {
  border: 1px solid #c8ccd1;
}
.thumbcaption .magnify a {
  display: block;
  width: 15px;
  height: 11px;
  background-image: linear-gradient( transparent,transparent ),url(data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%20standalone%3D%22no%22%3F%3E%0A%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2011%2015%22%20width%3D%2215%22%20height%3D%2211%22%3E%0A%20%20%20%20%3Cg%20id%3D%22magnify-clip%22%20fill%3D%22%23fff%22%20stroke%3D%22%23000%22%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20id%3D%22bigbox%22%20d%3D%22M1.509%201.865h10.99v7.919h-10.99z%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20id%3D%22smallbox%22%20d%3D%22M-1.499%206.868h5.943v4.904h-5.943z%22%2F%3E%0A%20%20%20%20%3C%2Fg%3E%0A%3C%2Fsvg%3E%0A);
  user-select: none;
  margin: 4px;
}
```
